# 路径配置
app.pdf.input-folder=${inputPath:./pdf_input}
app.pdf.bak-folder=${bakPath:./pdf_bak}
app.excel.output-folder=${outputPath:./excel_output}

app.excel.filename-prefix=cufflinksDetails
app.excel.max-files-per-day=99
app.excel.sheet-name=orderDtails
# 初始序号配置
app.excel.initial-index=1
# 产品名称映射配置文件
app.mapping.product-name-file=product-name-mapping.properties

# 字符编码配置
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

app.ocr.language=eng
# 定时任务配置
scheduler.cron=0 * * * * ?

#app.pdf.input-folder=/Users/mac/Desktop/orderManagementFile/Cufflinks/pdf_input
#app.pdf.bak-folder=/Users/mac/Desktop/orderManagementFile/Cufflinks/pdf_bak
#app.excel.output-folder=/Users/mac/Desktop/orderManagementFile/Cufflinks/excel_output
