# 产品变量映射配置文件
# 格式：名称=中文名称
# 修改此文件后需要重启应用才能生效

# 1月份
1 Garnet Glow=一月
# 2月份
2 Amethyst Dream=二月
# 3月份
3 Aquamarine Sky=三月
# 4月份
4 Diamond Twilight=四月
# 5月份
5 Emerald Morning=五月
# 6月份
6 Pearl Blossom=六月
# 7月份
7 Ruby Rose=七月
# 8月份
8 Peridot Breeze=八月
# 9月份
9 Sapphire Night=九月
# 10月份
10 Pink Tourmaline=十月
# 11月份
11 Citrine Light=十一月
# 12月份
12 Topaz Snow=十二月

# 包装盒类型
Small Square Box=小方形礼盒
Box Box=长方形礼盒
Big Square Box=大方形礼盒
#=方形开窗木盒
#=长方形开窗木盒
BOX=Box-长方形木盒
Oval Box=Oval Box-椭圆形开窗木盒
Square Box=Square Box-方形开窗木盒
