Style1=Style 1
Style2=Style 2
Style3=Style 3
Style4=Style 4
Style5=Style 5
Style6=Style 6
Style7=Style 7
Style8=Style 8
Style9=Style 9
Style10=Style 10
Style11=Style 11
Style12=Style 12
Style13=Style 13
Style14=Style 14
Style15=Style 15
Style16=Style 16
Style17=Style 17
Style18=Style 18
Style19=Style 19
Style20=Style 20
Style21=Style 21
Style22=Style 22
Style23=Style 23
Style24=Style 24
Style25=Style 25
Style26=Style 26
Style27=Style 27
Style28=Style 28
Style29=Style 29
Style30=Style 30
Style31=Style 31
Style32=Style 32
Style33=Style 33
Style34=Style 34
Style35=Style 35
Style36=Style 36
Style37=Style 37
Style38=Style 38
Style39=Style 39
Style40=Style 40
Style41=Style 41
Style42=Style 42
Style43=Style 43
Style44=Style 44
Style45=Style 45
Style46=Style 46
Style47=Style 47
Style48=Style 48
W55=W55
W57=W57
See the attached = 见附图
Character Design = 人物头像(见附图)
Pet Design = 宠物头像(见附图)
